services:
  maildev:
    build:
      context: .
      dockerfile: maildev.Dockerfile
    ports:
      - ${MAIL_CLIENT_PORT}:1080
      - ${MAIL_PORT}:1025

  db:
    image: docker.io/bitnami/mariadb:10.6
    container_name: db
    environment:
      ALLOW_EMPTY_PASSWORD: yes
      MARIADB_ROOT_HOST: ${DB_HOST}
      MARIADB_DATABASE: ${DB_DATABASE}
      MARIADB_ROOT_PASSWORD: ${DB_PASSWORD}
      MARIADB_PASSWORD: ${DB_PASSWORD}
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - podback

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - '8091:80'
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - PMA_USER=${DB_USERNAME}
    depends_on:
      - db
    links:
      - db:db
    networks:
      - podback

  # Uncomment to use redis
  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379

networks:
  podback:
    driver: bridge
